### ISSUE TITLE
Map setup

### ISSUE THREAD

**Issue by Granik24** [PlayFriik/Annihilation#1]
I have question, how I can setup maps?

**Comment by PlayFriik** [comment]
1. Upload your own map into your server folder (where some other maps are).
2. Go into your server and type /map edit <yourMapName>.
3. Open file maps.yml. You can find it from Annihilation plugin's folder.
4. There you can see: spawnpoints, nexuses, enderfurnaces etc.
5. Now go into minecraft again and start looking coords with pressing F3 on your keyboard and put all required coords into that maps.yml.
6. When it's done, then type /map save <yourMapName>.

I know that the setuping may take pretty long time, but it can't be that much shorter.

**Comment by Granik24** [comment]
Thank you for your respond. Nice to see that!

**Comment by PlayFriik** [comment]
No problem! :)

**Comment by PlayFriik** [comment]
So.. Is it resolved now?

**Comment by Granik24** [comment]
Sure, it is. Thanks again!
