### ISSUE TITLE
I just wanna request more kits from shotbow network

### ISSUE THREAD

**Issue by i998979** [PlayFriik/Annihilation#4]
hello PlayFriik
MCTyler just said i should ask you about the annihilation plugin kits
i want you to add more kits from shotbow annihilation
this is the post
https://github.com/MCTyler/CrafterNexus/issues/10#issuecomment-118183985
so, i hope you can do it
(sorry for my bad english because i am cantonese...)

**Comment by PlayFriik** [comment]
No, sorry. I am just updating the plugin if new CraftBukkit version comes out, nothing more, sorry.
I just don't have time for doing plugins what I get paid for and this free plugin.

**Comment by PlayFriik** [comment]
Vault - http://dev.bukkit.org/bukkit-plugins/vault/files/50-vault-1-5-3/
Bukkit - http://tcpr.ca/files/bukkit/bukkit-1.8.7-R0.1-SNAPSHOT-latest.jar
CraftBukkit - http://tcpr.ca/files/craftbukkit/craftbukkit-1.8.7-R0.1-SNAPSHOT-latest.jar
